# Generated by Django 5.1.2 on 2024-11-26 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0006_region_customer_order_orderproduct_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shippings', to='loft.customer', verbose_name='Покупатель'),
        ),
    ]
